### PR TITLE
adding Kelvin as a member

### PR DESCRIPTION
**Pull request by Kelvinrr**

### CODE REVIEW

**Review by jlaura — APPROVED** [review]

**Comment by jlaura** [comment]
I believe this requires one other, non-USGS approving review.

**Comment by Kelvinrr** [comment]
Gonna ping people for additional review, @acpaquette @rbeyer @AndrewAnnex @KrisBecker

**Review by rbeyer — CHANGES_REQUESTED** [review]
I approve of adding Kelvin.  While we are PRing the Members list, let's also remove Robin.

**Comment by Kelvinrr** [comment]
@rbeyer removed Robin

**Review by rbeyer — APPROVED** [review]

**Pull request merged**
