### PR TITLE
added stubbed notes for sept 2023 meeting

### PR DESCRIPTION
**Pull request by Kelvinrr**

### CODE REVIEW

**Comment by Kelvinrr** [comment]
@KrisBecker Before we merge this are there any topics you want to add ahead of the meeting? Seems there are often topics you want to talk about that weren't in the agenda and I think considering we are usually pretty light on topics anyways, we can get anything added ahead of the meeting.

**Comment by KrisBecker** [comment]
@Kelvinrr thanks for the opportunity however I will be away on vacation for the next two weeks.

**Comment by astrostu** [comment]
(Note: I've not done a pull request before so not sure if I did it right to add a topic.)

**Comment by jlaura** [comment]
@astrostu No topic was added and I do not see another open PR. What are you wanting to get added @Kelvinrr can likely be convinced to add it.

**Review by jlaura — APPROVED** [review]

**Comment by astrostu** [comment]
Sigh. I tried to add this:  "Are important issues being stale'd out without being addressed?"

**Comment by Kelvinrr** [comment]
@astrostu Added it, on of my topics is gonna be super fast so probably not an issue to add another. 

I also added names of people who originally brought up the topic to make it easier to know who should seed the convo.

**Pull request merged**
